use failure::Error;

pub fn app() -> Result<(), Error> {
    Ok(())
}
